### ISSUE TITLE
To learn how to use Screenplay with NUnit, devs should be able to read a tutorial

### ISSUE THREAD

**Issue by craigfowler** [csf-dev/CSF.Screenplay#154]
The [tutorial wiki page relating to NUnit](https://github.com/csf-dev/CSF.Screenplay/wiki/NUnitTutorial) is incomplete. It must be completed.

## Tasks remaining
- [ ] Create the simple "To do" app which the tutorial code would test
- [ ] Fill out the integration config (the tutorial shows how to create an empty one, but we need more than that).  It needs at minimum some info about how to set up browser testing
- [ ] Actually follow the tutorial start-to-finish in order to see some passing tests.  Further tasks might be identified if this doesn't work.

**Comment by craigfowler** [comment]
I need to fix some things in the nunit docco.

* It still refers to a builder that I deleted
* There's a typo in the sample code
